### ISSUE TITLE
Fieldmap gets locked on search for trait values - observed but not repeated

### ISSUE THREAD

**Issue by kadreher** [kddart/kdsmart-apks#1]
Greetings,

I wrote a description below - but then I think that I figured out the cause of the problem and submitted it in a subsequent comment. I apologize for raising a red flag when it was a data issue not a software issue,

I had a trial on KDSmart on my phone (2.0.63). I used the Fieldmap to try to do a search for a particular trait value. Once I did that, I could not do a search for any other kind of attribute in the field map. I restarted the phone. I did a force quit of the application. I rotated the screen in case some menu item was hidden. But, I could never get out of the "Active Traits" search mode. This did not affect another trial downloaded to the same phone. I tried to replicate it in the second trial on my phone and also on the Android emulator on my computer and could not. So, I cannot give a detailed explanation for what caused this problem. But, I will keep trying to figure out what confounding factors might have caused it. The trait was EH (ear height) and the trial is Libro_Agueda_Yoro_Honduras.

**Comment by kadreher** [comment]
Oh gosh - I just realized what the problem was! 

This trial did not have any plot metadata so it was not possible to search on the other attributes. When I added some tags, then I was able to search on the tags.

I apologize for this error report. You can probably close it!

**Comment by barrow-wight** [comment]
Closed on request by submitter
