### ISSUE TITLE
Request to make "Block" and "Entry" Plot Attributes by default

### ISSUE THREAD

**Issue by kadreher** [kddart/kdsmart-apks#2]
Greetings,

One of our applications (Maize Fieldbook) exports a file that typically has "Entry" and "Block" as column headers. The software automatically maps them to "Trait." Would it be possible to make these "Plot attributes" by default, please?

Many thanks,
kate

**Comment by barrow-wight** [comment]
In KDSmart version 3 (currently approaching Beta test status) the "Block" heading (and potential synonyms) will be a property of Plot and Individual (e.g. "Plot Block" - augmenting "Plot Row/Column") so we can't do it for that.

Similarly, it is likely (although not yet definite) that "Entry" is going to be mapped to another property.  

I 'm happy to meet with you to go over some of the coming changes and explore alternatives that don't adversely affect the future development KDSmart.
