### ISSUE TITLE
KDXplore - Cannot create box plots from some right-click buttons

### ISSUE THREAD

**Issue by kadreher** [kddart/kdsmart-apks#3]
When I right click on a trait from the curation window, it says that there is no data to plot in the box plot. But, if I right click from the summary statistics or from the left lower menu (trait/attribute list), I can create a box plot.

[box_plot_differential_availability.pptx](https://github.com/kddart/kdsmart-apks/files/765289/box_plot_differential_availability.pptx)

I think that you probably want users to be able to create a box plot from all three of these right-click menus. Is that correct or am I doing something wrong on getting a box plot from the tabular view of the data?

Thank you.

**Comment by kadreher** [comment]
I am sorry that this should actually be under KDXplore.

**Comment by barrow-wight** [comment]
Invalid for this  product.
Please re-submit under correct product.

**Comment by kadreher** [comment]
Greetings,

Is there a way for you to change the queue for this issue so that I do not have to resubmit it, please?

Sincerely,
kate
