### ISSUE TITLE
Search tool on Fieldmap is not working properly

### ISSUE THREAD

**Issue by claudiocah** [kddart/kdsmart-apks#4]
On fieldmap: *Any time that you type something in the filter,
then tick the checkbox for any value, and finally click on the button to paint the cells according your criteria, the app is showing wrong information

-attached csv file (as an example)
also screen shoots with the details
[issuefilter.zip](https://github.com/kddart/kdsmart-apks/files/797091/issuefilter.zip)

**Comment by barrow-wight** [comment]
Release 2.0.65 will be released shortly with a fix for this problem.

Thanks so much for the screenshot and the Trial data. This helped a lot in tracking down the problem.

**Comment by barrow-wight** [comment]
Release 2.0.65 is now in the Play Store.
Please update your app to get the fix for this issue.
